2024-04-09 15:38:33,705 INFO    MainThread:1542241 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-09 15:38:33,705 INFO    MainThread:1542241 [wandb_setup.py:_flush():76] Configure stats pid to 1542241
2024-04-09 15:38:33,705 INFO    MainThread:1542241 [wandb_setup.py:_flush():76] Loading settings from /accounts/grad/phudish_p/.config/wandb/settings
2024-04-09 15:38:33,705 INFO    MainThread:1542241 [wandb_setup.py:_flush():76] Loading settings from /accounts/grad/phudish_p/mllm/summarization/Experiment_3/wandb/settings
2024-04-09 15:38:33,705 INFO    MainThread:1542241 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2024-04-09 15:38:33,705 INFO    MainThread:1542241 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-09 15:38:33,705 INFO    MainThread:1542241 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'summarization/Experiment_3/t5.py', 'program_abspath': '/accounts/grad/phudish_p/mllm/summarization/Experiment_3/t5.py', 'program': '/accounts/grad/phudish_p/mllm/summarization/Experiment_3/t5.py'}
2024-04-09 15:38:33,705 INFO    MainThread:1542241 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-09 15:38:33,705 INFO    MainThread:1542241 [wandb_init.py:_log_setup():521] Logging user logs to /accounts/grad/phudish_p/mllm/summarization/Experiment_3/wandb/run-20240409_153833-h32wnhp2/logs/debug.log
2024-04-09 15:38:33,705 INFO    MainThread:1542241 [wandb_init.py:_log_setup():522] Logging internal logs to /accounts/grad/phudish_p/mllm/summarization/Experiment_3/wandb/run-20240409_153833-h32wnhp2/logs/debug-internal.log
2024-04-09 15:38:33,705 INFO    MainThread:1542241 [wandb_init.py:init():561] calling init triggers
2024-04-09 15:38:33,705 INFO    MainThread:1542241 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-04-09 15:38:33,705 INFO    MainThread:1542241 [wandb_init.py:init():611] starting backend
2024-04-09 15:38:33,705 INFO    MainThread:1542241 [wandb_init.py:init():615] setting up manager
2024-04-09 15:38:33,706 INFO    MainThread:1542241 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-04-09 15:38:33,708 INFO    MainThread:1542241 [wandb_init.py:init():623] backend started and connected
2024-04-09 15:38:33,711 INFO    MainThread:1542241 [wandb_init.py:init():715] updated telemetry
2024-04-09 15:38:33,727 INFO    MainThread:1542241 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-09 15:38:33,835 ERROR   MainThread:1542241 [wandb_init.py:init():774] encountered error: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2024-04-09 15:38:33,898 ERROR   MainThread:1542241 [wandb_init.py:init():1199] The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
Traceback (most recent call last):
  File "/accounts/grad/phudish_p/.local/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
          ^^^^^^^^^
  File "/accounts/grad/phudish_p/.local/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.AuthenticationError: The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
2024-04-09 15:38:34,901 WARNING MsgRouterThr:1542241 [router.py:message_loop():77] message_loop has been closed
